pages:
  stage: deploy
  tags:
    - shell
  script:
    - mkdir -p public
    - cp index.html public/
    - cp -r assets public/ || true
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"